### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by RedondoBoony** [hdurdle/harmony#3]
Hi, is this still supported?

Trying to use the code, while using my account. 
GetUserAuthToken(username,password) with my account gives me:
"The remote server returned an error: (400) Bad Request"

Thanks 

Redondo

**Comment by hdurdle** [comment]
Hi, there is no support, this is just a library I wrote and found useful and I use GitHub to store the repository. The code in the repo works on my systems (Win 8.1, Visual Studio 2013) against two Harmony Hubs. If you find out what caused your issue, do suggest changes to improve things for the next person.
