### ISSUE TITLE
HarmonyConsole usage

### ISSUE THREAD

**Issue by Slion** [hdurdle/harmony#5]
I can run -g and I get the token and Current Activity: PowerOff.
However when I try -l to get the list of devices I only get the help.
I must be missing something.
Do you have more usage examples?

**Comment by hdurdle** [comment]
The -l option takes a parameter of either a to list activities or d to list devices.

**Comment by Slion** [comment]
To list my activities I should then run something like:
`HarmonyConsole.exe -i <ip-address> -u <user-name-email> -p <password> -l a`
To list my devices I should then run something like:
`HarmonyConsole.exe -i <ip-address> -u <user-name-email> -p <password> -l d`
Is that right?
