### ISSUE TITLE
How to list commands from a device?

### ISSUE THREAD

**Issue by Slion** [hdurdle/harmony#7]
Is that possible somehow?

**Comment by hdurdle** [comment]
Yup!

`HarmonyConsole.exe -i <ip> -u <Logitech-Email> -p <Logitech-Password> -d <Device-ID>`

Check the source in HarmonyConsole for how this works.  You'll need to get the Device ID first with:

`HarmonyConsole.exe -i <ip> -u <Logitech-Email> -p <Logitech-Password> -l d`

**Comment by Slion** [comment]
Thanks, I implemented it ;) Before it was listing the Control Groups.

**Comment by hdurdle** [comment]
Hah brilliant! I didn't think I remembered writing it! Thanks for the work. :)
